name: Python with contexts

on:
 push:
   branches: [main]

env:
  GLOBAL_ENV: default

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    outputs:
      greet-message: ${{ steps.set-output.outputs.message }}

    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v5
       with:
         python-version: ${{ matrix.python-version }}

     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt

     - name: Use repository variable
       run: echo "Global ENV is $GLOBAL_ENV"

     - name: Use created repository variable
       run: echo "Variable is ${{ vars.PY_VAR }}"

     - name: Use secret
       run: echo "Using API Key:${{ secrets.API_KEY }}"

     - name: Run Python app
       run: python app.py

     - name: Set output value
       id: set-output
       run: echo "message=Hello from Python build job" >> $GITHUB_OUTPUT

  deploy:
     needs: build
     runs-on: ubuntu-latest

     steps:
       - name: Use output from build
         run: echo "Received:${{ needs.build.outputs.greet-message }}"

       - name: Print created repo variable
         run: echo "Deploying in:${{ vars.PY_VAR }}"
